cli.js, index.js, readme.md
Publish Add support for `--tag xx`, which publishes under a given dist-tag. Closes #45.
=> Add --tag option

index.js, package.json
Fixes #69.
Just waiting for a new version of listr to be published then I can bump the version.
=> Use listr skip API to skip publishing private packages

index.js
`np` already does a dirty check so any changes were likely caused by doing a clean build prior to `npm version` and these files can be staged with a "version" npm run script and included in the version bump commit.
Fixes #75.
=> Specify --force with npm version to skip dirty check

index.js, test.js
Tried to implement #70.
Extracted the prerequisite check into a separate subtask list with the following tasks
1. Check Node.js and npm version
- This task will be skipped if Node.js is < 6. Or should we keep the previous logic without `skip` function?
2. Fetch remote changes (necessary to be executed before 3 but doesn't feel right in this place)
3. Check git tag existance
- I execute the command `git rev-parse --quiet --verify refs/tags/NEW_TAG`. Anything else I should use?
Feedback is more then welcome because I'm not totally sure about the implementation.
// @sindresorhus @jamestalmage @ianstormtaylor
=> add git tag check - fixes #70

index.js, lib/git.js, lib/prerequisite.js
Did some tweaks. Also used `skip` to test the npm version. If the node version is less then 6.0.0, that check is marked as skipped.
Wanted to extract the `git` and `prerequisite` tasks in separate files (e.g. `lib/git.js` and `lib/prerequisite.js`). Currently the codebase looks "complex", although it is all pretty straightforward. I believe by extracting those in separate files, it will look cleaner. I can do it in this PR or we can discuss it in a separate issue if you want.
=> split out some tasks into separate files and some other tweaks

package.json
Since version `0.6.x`, listr supports custom renderers. Nothing improved for `np` directly, but it would be nice if I could verify everything is working correctly with `np` :). It could also help to fix GPG password prompt #79.
I linked this version of `listr` locally to `np` and ran it a couple of times. Everything seems to be working as it was.
Feel free to close the issue if you don't see direct impact on this project.
=> :arrow_up: listr@0.6.1

cli.js, index.js, lib/interactiveui.js, lib/prerequisite.js, lib/ui.js, lib/version.js, package.json, readme.md, test.js, test/version.js
This PR adds a interactive ui when np runs without arguments as suggested in #52.
features:
- choose increment type (e.g. patch) or specify own version (e.g. 0.1.3)
- choose NPM dist-tag for pre-releases (except packages with `"private": true`)
- user can choose from a list of already existing tags for this package or
- specifiy a custom tag except latest
- show info about which version you're going from and to.
- user have to confirm the release to prevent accidental publishing of wrong versions
Edit(sindresorhus):
**You can install this PR with: `$ npm i -g 'zinserjan/np#interactive-ui'` and run it with `$ np`.**
=> Add interactive UI

lib/ui.js
[npm dist-tag](https://docs.npmjs.com/cli/dist-tag) is currently [not supported in Nexus](https://issues.sonatype.org/browse/NEXUS-9862).
This commit uses [npm view](https://docs.npmjs.com/cli/view) to retrieve the dist tags so that people using Nexus as a [npm private registry](https://books.sonatype.com/nexus-book/reference/npm.html) can use np to publish pre-release versions of their modules.
=> Use npm view instead of dist-tag

cli.js, index.js, lib/ui.js, lib/util.js, package.json, test.js
Additionally reads the `package.json` file once and passes it onto `ui.js` and `index.js`
Fixes #106
=> Throw a more user-friendly exception

cli.js, index.js, readme.md
=> Add `--no-publish` flag

index.js
The npm scripts `preversion` and `version` could fail for legitimate reasons
(examples include: auto-updating CHANGELOG.md, or performing a sanity check
on that same file). The --force switch will ignore any of these errors and
continue with publishing the new version regardless.
This change surfaces the errors (which were previously silent).
NOTE: since `np` already checks for a dirty working environment, --force is
superfluous at the `npm version` stage.
An example of the new output seen when `version` fails is similar to:
```bash
$ ../np/cli.js --no-cleanup --no-publish
Publish a new version of some-module (1.0.2)
? Select semver increment or specify new version patch (1.0.3)
? Will bump from 1.0.2 to 1.0.3. Continue? Yes
✔ Prerequisite check
✔ Git
✔ Running tests
✖ Bumping version …
```
=> Surface errors from failed 'version' scripts

lib/prerequisite.js, package.json
This PR fixes #134 by using `yarn check --integrity`. This check fails if the `package.json` doesn't match the `yarn.lock` file.
I chose to throw a custom error with a step on how to fix it instead of just throwing the output of that check which looks like
> error Lockfile does not contain pattern: "rxjs@^5.2.0"
> error Integrity hashes don't match, expected "730f87896cc809a098033ac423e0699d2693323371a33
> cc40cd276ac77665687" but got "e5eb319a8d0de9c04a07da3ffd015c0235eb0cd732e17e7f3ecae603fb64a6c0"
> error Found 2 errors.
> yarn check v0.22.0
> info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
// @gillesdemey @rarkins
=> Check yarn.lock integrity - fixes #134

lib/prerequisite.js
The dist tag check is not executed when `--no-publish` is used.
=> Disable dist-tag check when running with `--no-publish` - fixes #140

index.js
yarn's version script has slightly different semantics / operation to npm's. In particular, [`npm` will not search the parent tree for `.git` folders](https://github.com/npm/npm/blob/bf3bd1e4347ee2c5de08d23558c4444749178c8b/lib/version.js#L182-L184), however [yarn will](https://github.com/yarnpkg/yarn/blob/e7e2aa7a5252aeb8ca9760b0a2dc6ee5f923f964/src/cli/commands/version.js#L130-L139).
Searching parent tree for `.git` enables having multiple packages contained within their own subfolders of a single repository, for example:
```
.
├── .git
├── README.md
├── some-module
│   ├── package.json
│   ├── index.js
│   └── yarn.lock
└── another-thing
   ├── package.json
   ├── index.js
   └── yarn.lock
```
With this change, it will enable:
```
cd some-module
np
```
=> Use `yarn version` when available

index.js, lib/prerequisite.js
Fixes #144. The `yarn check` command has extra behaviour outside of checking if the lockfile needs to be updated and the message it fails with is a little confusing, which is causing some of the problems discussed in #144. Using `--frozen-lockfile` on install will also guarantee that a mismatch will cause a failure instead of updating the lockfile, but without the extra requirements `check` has.
Here's a sample of the output:
```
? Select semver increment or specify new version patch 	4.2.3
? Will bump from 4.2.2 to 4.2.3. Continue? Yes
✔ Prerequisite check
✔ Git
✔ Cleanup
✖ Installing dependencies using Yarn
→ info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this com…
Running tests
Bumping version
Publishing package
Pushing tags
✖ Command failed: yarn install …
```
=> Swap prerequisite yarn check with frozen lockfile on install

lib/publish.js
npm now exits with:
```
npm ERR! publish Failed PUT 401
npm ERR! code E401
npm ERR! This operation requires a one-time password from your authenticator.
npm ERR! You can provide a one-time password by passing --otp=<code> to the command you ran.
npm ERR! If you already provided a one-time password then it is likely that you either typoed
npm ERR! it, or it timed out. Please try again.
```
Fixes #205.
=> Fix check for OTP input

index.js
refs #216, #203, etc
I've genuinely been pulling my hair out with np for the last 3 days. I've done my absolute best to try to contribute a fix because I love this tool, but I'm utterly lost 😭 
I've tried to fix the npm publish, but I just don't understand how exec/execa/observable are all related.
Instead I've tried to add yarn publish support, but although the publish happens, the flow of control never returns back to listr it seems, so it sits and hangs forever, and never gets as far as pushing the tags. I am at a loss for how to debug.
This PR includes that attempt.
Can someone who understands listr, execa, etc etc take a look and see if they can find an easy fix?
I'd also love to know as well:
- what does the streamToObservable wrapper in index.js & observableFromPublish code in …
=> Use `yarn publish` for Yarn

index.js
During publish the `version` script was being run twice, which breaks scripts that do things like bump changelogs. `yarn publish` automatically does the same thing as `yarn version` so the first step can be skipped.
=> Don't run version script twice when publishing with Yarn

lib/ui.js, lib/util.js, package.json, test/hyperlinks.js
This PR implements #233. Feedback welcome. It also links the issues inside the commit.
=> Linkify commits - fixes #233

lib/ui.js, lib/util.js
Trying the new version of np on a project that doesn't define the repository entry in `package.json` results in this error
> Cannot read property 'url' of undefined
This is related to commit 263b0c3c92365525c2b1887b069a6ca9d0c508ef (linkify commits) which assumes that the repository entry is always present in `package.json`, which is not always the case.
This simply check that `pkg.repository` is defined before using `pkg.repository.url`.
=> Handle undefined repository URL in the linkify commits feature

lib/ui.js, package.json
This PR resolves #238 and cleans up the `ui.js` file quite a bit because the inquirer prompt messages can now be merged. :tada:
=> Show list of commits before prompt - fixes #238

index.js
I noticed that in yarn mode, np still runs `npm test`.
As the way scripts are run differs slightly between yarn & npm, this is important in some cases.
This is the only remaining place where np uses npm in yarn mode.
- Removing final usage of npm whilst in yarn mode
=> Switch between npm & yarn for tests

index.js
This allows np to create a tag on a private package, it sort of reverts https://github.com/sindresorhus/np/pull/235.
For public packages, the tag will be created using yarn publish.
Private package:
```
$ ../np/cli.js 1.0.1
✔ Prerequisite check
✔ Git
✔ Cleanup
✔ Installing dependencies using Yarn
✔ Running tests using Yarn
✔ Bumping version using Yarn
↓ Publishing package using Yarn [skipped]
→ Private package: not publishing to Yarn.
✔ Pushing tags
```
Public package:
```
$ ../np/cli.js 1.0.2
✔ Prerequisite check
✔ Git
✔ Cleanup
✔ Installing dependencies using Yarn
✔ Running tests using Yarn
↓ Bumping version using Yarn [skipped]
→ Public package: version will be bumped using yarn publish.
✔ Publishing package using Yarn
✔ Pushing tags
```
---
cc @gpoole @ErisDS
=> Fix yarn version bump for private packages

lib/prerequisite.js
Skip the task 'Ping npm registry' when the option `--no-publish` is
present on the command line, as this task is only useful when publishing
a package.
I tried to run `np --no-publish` with a custom npm registry ([Nexus](https://help.sonatype.com/display/NXRM3/Node+Packaged+Modules+and+npm+Registries)) set in `~/.npmrc` and this fails without this patch as it tries to ping the npm registry, which is unfortunately [not supported on Nexus](https://issues.sonatype.org/browse/NEXUS-13434).
=> Skip "Ping npm registry" task when using `--no-publish`

cli.js
As I am a bit fan of not installing globally and love the Idea of enhancing the default `npm publish` with this nice tool, I added it to my `script.prepublishOnly` hook.
But when I testet my integration I didn't want to publish and aborted with ctrl+c. But the problem is, that np currently returns with exit code 0 in this case which in turn started publishing anyway, but without all the nice checks from np.
To avoid this I thought about catching the SIGINT in the cli and end the process with a non zero exit code. (just picked 100 before I saw that you are just exiting with 1 in an error case. I can change this to 1 as well or we leave them separate to distinguish them, as you prefer)
I think this makes it more convenient when integrating it in other scripts as well.
Any opinions of …
=> Exit with non-zero exit code on SIGINT

cli.js, index.js, lib/publish.js, readme.md
This pull request is a way to solve [this issue](https://github.com/sindresorhus/np/issues/264). With these changes, the `np` users can specify the current folder or tarball to be published as a package via `--content` flag.
Example
```bash
$ np 1.0.2-beta.3 --tag=beta --content=dist 
```
- NodeJS `path` functions are not required since `np` runs based on the current `process.cwd()`;
- Checked with NPM and Yarn and in both approaches are working properly;
---
Fixes #264
=> Add ability to publish a subdirectory

index.js
This addresses https://github.com/sindresorhus/np/issues/270
According to the `rxjs` v5 to v6 migration guidelines, the `catch` operator has now been changed to `catchError`.
https://github.com/ReactiveX/RxJS/blob/HEAD/MIGRATION.md#howto-convert-to-pipe-syntax
=> Fix outdated rxjs pipe function

lib/ui.js
For "big" projects (that have a lot of commits), Git commit abbreviation hash have a dynamic length (contrary to "small" projects that have a fixed length of 7):
[Commit introducing this change in the Git source code](https://github.com/git/git/commit/e6c587c733b4634030b353f4024794b08bc86892)
For example, running np on a "big" project (like the Vue.js source code) yields this error:
> np
Publish a new version of vue (current: 2.5.17-beta.0)
✖ Cannot read property '1' of null
As the command
> git log --format='%s %h' 19552a82a636910f4595937141557305ab5d434e..HEAD
returns lines with a hash of 8 characters:
```
chore(package.json): Add sideEffects: false field in package.json (#8099) 5e3823a5
chore: new sponsor 654e5f15
chore(typo): no dots at the end of the comments (#8087) 1abb944a
``` …
=> Fix dynamic commit hash abbreviation length

readme.md
In macOS Sierra 10.12.2 and later, it’s recommended to add both `AddKeysToAgent` and `UseKeychain` to one’s `~/.ssh/config`. I’ve updated the the tip accordingly, shortened it a bit, and linked to GitHub Help where connecting to GitHub using SSH is explained in more detail.
This information is based on [Apple’s technical note TN2449](https://developer.apple.com/library/archive/technotes/tn2449/_index.html) and [GitHub’s support article](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-ssh-key-to-the-ssh-agent).
=> Update tip regarding SSH updates in macOS Sierra 10.12.2

lib/ui.js, lib/util.js
If no tags are found, `git describe` will return an error, causing the program to exit. From my testing and understanding, this wont happen because of
```
if (!result) {  
return false;  
}
```
but I am not completely sure. I would appreciate any feedback.
---
Fixes #283
=> Add comparison link under commits

lib/prerequisite.js, lib/version.js, test/version.js
The current Node.js version check (which is used to determine whether to skip the npm version check) is actually the wrong way around:
https://github.com/sindresorhus/np/blob/cec8e001794170db18d6c9cb468644d97441e697/lib/prerequisite.js#L93
For example, `version.isVersionLower('6.0.0', 'v11.6.0')` returns `false`, therefore *not* skipping the following npm version check:
https://github.com/sindresorhus/np/blob/cec8e001794170db18d6c9cb468644d97441e697/lib/prerequisite.js#L97
Since most installations nowadays include a newer npm version, the error was probably rarely thrown (even though the task ran on newer Node.js versions). However, Node.js v11.6.0 includes npm v6.5.0-next.0, a pre-release version. [Pre-release versions do not satisfy by …
=> Remove npm version check

lib/ui.js
The newly introduced question of whether to publish scoped packages publicly or not has a dangerous default for those of us who use scoped packages internally.
Just as npm itself defaults to publishing scoped packages privately, so should `np`.
An accidental public publish is not that easy to revert and can cause quite some problems, depending on what code it involved.
=> Default to not publish scoped packages publicly

index.js, lib/git-util.js, lib/git.js
This fixes #90.
Let me know if there should be added a test for this to prevent future regressions.
=> Gracefully handle branch not having an upstream

cli.js, lib/ui.js
Added the check for no-publish to be only triggered when publish is true. 
I Would like to add the skip name check as another flag personally. In case people still choose to publish packages.
=> Skip npm name check when `--no-publish` is passed

index.js, lib/git-util.js, lib/git.js, lib/prerequisite.js, lib/ui.js
This follows up https://github.com/sindresorhus/np/pull/289#discussion_r246272308, #321 and #322.
Note that I didn't move [the `push` command](https://github.com/sindresorhus/np/blob/master/index.js#L154) to `git-util.js` since it uses [`exec`](https://github.com/sindresorhus/np/blob/master/index.js#L21).
=> Move all Git utility commands to `lib/git-util.js`

source/npm-util.js
=> Ensure package exists when checking tags

source/git-util.js
This makes `np` correctly print out the commit history in case no previous _annotated_ tags are found but previous _unannotated_ tags do exist. See more on this in #338.
=> Detect all tags in `latestTag()`

source/npm-util.js
Despite #331 / #179 claiming to be fixed, I ran into exactly the same issue when trying to publish a new module's first version as a prerelease.
I took a look at the code and found that the check introduced in #331 checked `JSON.parse(error.stdout).code` rather than the correct ``JSON.parse(error.stdout).error.code`, which meant it never equaled `'E404'` (or npm has changed its format between that PR and my test, I used npm `6.7.0`)
~~In addition to the error fixed in #331, there was an additional error as well in `collaborators()`, which also it no longer properly detected 404 errors.~~
~~Reason for that second error is that npm has changed the human readable error it outputs and there's no json output for that command. I therefore added a new `checkExistance()` method which utilizes the …
=> Fix doing a prerelease as the first release

source/git-util.js, source/prerequisite-tasks.js
=> Verify locally installed Git version is >=2.11

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/issue_template.md, .github/pull_request_template.md
This adds a basic issue template, inspired by GitHub's default bug report template and [this template](https://raw.githubusercontent.com/stevemao/github-issue-templates/master/bugs-only/ISSUE_TEMPLATE.md).
Note that I added a single template for both bug reports and feature requests, but I could split it to two separate templates (this way, we'll also be able to take advantage of [GitHub's issue template feature](https://help.github.com/en/articles/creating-issue-templates-for-your-repository)).
Fixes #352.
=> Add issue and PR templates

readme.md, source/cli.js, source/index.js
=> Add `--no-release-draft` flag to skip opening a GitHub release draft page

readme.md
=> Add missing closing bracket in `readme.md`

source/cli.js, source/ui.js
=> Fix release draft not being opened when running `$ np <version>`

readme.md, source/cli.js, source/index.js
I would like to be able to disable running `npm test` but keep cleanup enabled because I have a custom testing script inside `prepublishOnly`.
Similar to #299, I have tests running twice (possibly three times with git hooks as well).
Fixes #428
=> Add `tests` option

readme.md, source/npm/util.js, source/ui.js
I've read the discussion in #103 and I though: why not put a PR with some initial work up and see where it takes us?
I'm currently checking if the project has either a `files` field specified in the `package.json` or an `.npmignore` file in the root folder and just warning about it.
Thoughts?
=> Warn if no files field in package.json or .npmignore file present

readme.md, source/index.js
External registry don't all support two-factor authentication.
For example, when using [Nexus as npm registry](https://blog.sonatype.com/using-nexus-3-as-your-repository-part-2-npm-packages), the command
```bash
> npm profile enable-2fa
```
fails with
```
npm ERR! code E400
npm ERR! 400 Bad Request - POST http://nexus.../content/groups/npm-all/-/npm/v1/tokens
npm ERR! A complete log of this run can be found in:
npm ERR!     ...npm/_logs/2019-06-20T09_24_05_833Z-debug.log
```
This change disables the two-factor authentication task for external registry so that we can continue to publish packages on Nexus.
=> Avoid enabling 2FA for packages published to external registries

source/index.js
For the doc of [hosted-git-info](https://github.com/npm/hosted-git-info):
> If the URL can't be matched with a git host, null will be returned
So `hostedGitInfo.fromUrl()` may return `null`, this commit fixed the issue.
Fixes #440
=> Fix pushing to uncommon Git hosts

source/npm/handle-npm-error.js
The Yarn OTP feature broke after it was added in #302 because, for some reason, the [`error.message` string](https://github.com/sindresorhus/np/blob/1834e960f3256a34fe7b897e2ee1682745981545/source/npm/handle-npm-error.js#L12) no longer contains the error message. `error.stderr` does contain it though, so using `error.stderr.includes('user TTY')` would be one solution to fix this problem.
However, @sindresorhus [was asking about "any better parts of the output we could test"](https://github.com/sindresorhus/np/pull/302#discussion_r237354430) on the original PR. It turns out, Yarn does have this now — it logs the following message when 2FA is enabled:
```
info Two factor authentication enabled.
```
That's why I decided to use `error.stdout.includes('Two factor authentication')` instead.
=> Fix Yarn OTP failure

readme.md, source/index.js
Fixes #480
This PR enables the [engine-strict](https://docs.npmjs.com/misc/config#engine-strict) configuration for `npm install` when np reinstalls the dependencies. This will raise an error if the project or its dependencies have an `engines.node` in package.json that are incompatible with the current environment.
A question: should this be applied to the `npm ci` case as well? I ran `npm ci --engine-strict` in a package whose `engines.node` was incompatible with the current Node version and it did not complain, whereas `npm install --engine-strict` did complain in the same situation. However, I did not test what happens when dependencies have mismatched engines. I also did not test using the npm config environment variable, only the command line flag. Perhaps an implementation quirk …
=> Enforce matching engines on npm install

source/npm/util.js, source/prerequisite-tasks.js
I experienced issues when working with np and referencing an external registry. Although I added
```
"publishConfig": {
"registry": "https://fooregistry.tld"
},
```
to my package.json file and having an additional reference in the local .npmrc-file, the check prerequisities command required a long time and finally failed. As #339 states an npm update might help, but my version was already 6.13.1.
The reason for my issue was that the `npm.collaborators`-command missed an additional arg option "--registry https://fooregistry.tld": This PR adds the required option and thus fixes the `npm.collaborators`-command in order to allow collaborator checks for external registries.
Although these issues are already closed, the error I experienced with the most-current np version comes closest to …
=> Fix checking collaborators when publishing to external registry

source/index.js, source/util.js
Fixes #474 
I wanted to write tests, but there doesn't seem to be an example of mocking out package.json contents anywhere. If you think it's necessary, I'll revisit when I can, and invest time in setting that up.
=> Publish non-private subdirectories when root is private

source/cli.js, source/npm/util.js, source/ui.js
Fixes #489 
Before:
After:
Adds an additional check whereby if a package's availability cannot be determined, it will prompt to attempt the publish anyway.
=> Allow publishing if availability check fails

source/npm/util.js, source/ui.js
Related https://github.com/sindresorhus/np/issues/391#issuecomment-511311938, https://github.com/sindresorhus/np/pull/399#issuecomment-531185309, https://github.com/sindresorhus/np/pull/399#discussion_r362760048
=> Show registry URL before publishing

package.json, source/ui.js
This PR escapes HTML special characters in commit messages included in the GitHub release notes body. This fixes #499.
I considered escaping the whole release body, but the relevant third-party stuff is only the commit messages, so I limited escaping to those. Maybe HTML will be needed in some future version of the generated release notes. Who knows. 🤷‍♂
=> Escape HTML in release note commit messages

source/util.js
The issue is that if you run np in a directory that isn't a package, `read-pkg-up` will throw an error.
// cc @lukeggchapman
=> Correctly detect if np isn't run in a package

source/ui.js
=> Fix scoped repo prompt showing even if package has already been published

source/cli.js
As mentioned in #515 by @pixelastic, the **releaseDraft** option is always overwritten by the default value of the CLI flags. Changing it within the package.json or .np-config is not possible.
=> Fix `releaseDraft` setting not working when set from config not CLI

package.json
@sindresorhus it appears I am just following you around from is-url-superb to npm-name to np, but that's just because I'm using np as it really is a better npm publish
This continues the work of shedding the dependency with a security issue by allowing the use of your just-published npm-name version
Cheers :-)
=> Update npm-name dependency

package.json, test/fixtures/listr-renderer.js, test/git-tasks.js, test/prerequisite-tasks.js
Fixes #384. Stubs were created for the commands as mention in my [comment](https://github.com/sindresorhus/np/issues/384#issuecomment-589947855).
The tests run serially because the stubbed `execa`-dependency is cached when loaded the first time (see https://github.com/avajs/ava/issues/1066 and https://nodejs.org/api/modules.html#modules_caching).
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#384: Add tests for pre-publish tasks](https://issuehunt.io/repos/40806530/issues/384)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>
=> Add pre-publish task tests

source/ui.js
Fixes #554 . Caused by always expecting ui to supply tag and not expecting it from cli.
=> Regression fix for tag not being taken when specified in CLI

readme.md, source/cli.js, source/git-tasks.js, source/git-util.js, test/git-tasks.js
=> Add support for specifying release branch

readme.md, source/cli.js, source/index.js, test/index.js
This adds a `--no-2fa` CLI option as discussed in #398 to bypass enabling 2FA on new packages.
The check is pretty trivial; if the 2Fa option is set to false, the task is skipped. Default value is true.
One of the reasons I'm wanting this is that I use `semantic-release` to handle releasing my packages, which requires not having 2fa enabled. I'm looking to use `np` for doing some pre-publishing of an upcoming package of mine, as `semantic-release` does not support `0.x.x` versions.
Fixes #398
Closes #515 (by superseding)
=> Add support for `--no-2fa` flag

package.json, source/git-util.js, source/index.js, test/index.js
Fixes #502.
Setup for tests:
1. setup branch protection fro some playground repository
2. publish new version with `np`
The tags should be pushed and the release draft should be created.
=> Create release draft even when pushing to protected branches failed

source/index.js
At least with Yarn v1.22.10 (the latest v1), `yarn run` prints straight quotes instead of curly quotes.
This was originally changed with https://github.com/sindresorhus/np/commit/0c46a2f6894eac8a429b1f9c036113e8d2022eb3 due to the suggestion at https://github.com/sindresorhus/np/pull/557#discussion_r456980965.
=> Fix error when Yarn cannot find test script

source/index.js, source/prerequisite-tasks.js, test/prerequisite-tasks.js
Standardizes the behavior of skipping and enabling tasks as discussed in https://github.com/sindresorhus/np/pull/513#issuecomment-696303588.
Apart from preview mode, there are now only two remaining cases where a task is skipped: “Pushing tags” when there’s no upstream branch ([source](https://github.com/sindresorhus/np/blob/5689d51ed1e7b0ad460f4bb4bd8cad6e9cd34a2c/source/index.js#L243-L245)) and when publishing failed ([source](https://github.com/sindresorhus/np/blob/5689d51ed1e7b0ad460f4bb4bd8cad6e9cd34a2c/source/index.js#L251-L253)). While the latter is certainly fine and expected, the former may be worthy of discussion. After all, the user may intentionally not have an upstream branch. For comparison, `np` also doesn’t skip “Running tests using npm” when there’s no `test` script. …
=> Standardize skipping and enabling tasks

.github/workflows/main.yml, test/integration.js
Fixes the breaking integration tests on Github actions. The checkout action on Travis CI fetches git submodules, whereas Github actions don't do it.
=> Fix integration tests on GitHub Actions

package.json, source/ui.js
Fixes #577.
Prompt with new files not part of the package is shown only in interactive mode.
=> Show prompt only in interactive mode

readme.md, source/cli-implementation.js, source/git-util.js, source/index.js, source/ui.js
Closes #478 
This is my proposal for the issue above.
- It adds the argument `--release-draft-only` to the CLI
- It adds the function `previousTagOrFirstCommit()` to get the tag which is before the one which we would have usually used
- Error if no tag found, which means the package hasn't been published yet
- Unreleased commits are ignored
Example of use case:
- **First commit**
- **Some changes**
- **1.0.0** (tag = v1.0.0)
- **More changes**
- **Bug fix**
- **1.0.1** (tag = v1.0.1) *(published on NPM, no release on GitHub)*
- **One last fix** *(unreleased)*
I do `np --release-draft-only`.
Behind the scenes, the np command is called with version **1.0.1** ["in mind"](https://github.com/sindresorhus/np/compare/master...Drarig29:master#diff-355e06507da68dfbe299f31276e205eac3ea53a573c6578cf1 …
=> Add `--release-draft-only` flag

source/git-util.js, source/index.js
Fixes #573.
Checks if `yarn.lock` is gitignored before throwing `yarn.lock file is outdated. Run yarn, commit the updated lockfile and try again.`
=> Check if yarn.lock is ignored before throwing error

readme.md, source/config.js, test/config.js, test/fixtures/config/homedir3/.np-config.cjs, test/fixtures/config/local3/.np-config.cjs
Maybe I'm missing something, but I can't get .np-config.js files to work in a folder with `type: module` in the package.json. This should fix that issue and also isn't inferring with anything else here AFAIK.
I also thought about adding the possibility for .mjs config files, for users without `type: module` but which want to write their config file in es module syntax. But that can also be in a seperate pull request and I wanted to keep it simple for now.
=> Add .cjs file ending for config file locations

source/git-util.js, source/ui.js
Fixes #593 
Here is the result with the repo [GhostText](https://github.com/GhostText/GhostText/) :
```
$ gh repo clone GhostText/GhostText
$ git checkout 17.12.11.910
$ np --release-draft-only
Create a release draft on GitHub for GhostText-browser (current: 0.0.0)
Commits:
- Fix: highlight text field when the connection happens, not when the field is focused  d88c3f7
- Feature: Automatically skip invisible textareas  b35eae9
- Fix: Remove unsupported blur event from CodeMirror  3cacd7d
- Refactor: Drop google-specific contenteditable  88f55ca
- Feature: support more contenteditable elements across the page  873f7c3
- Add HTML page for tests  e3df6ce
- Revert "Disable extensions-only deployment condition"  5726259
- Readme: improve usage  c07e2c8
- Readme: formatting/wording improvements …
```
=> Fix `--release-draft-only` flag

readme.md, source/cli-implementation.js, source/index.js
=> Add support for custom commit message

source/npm/util.js
Currently, `np` is failing to publish packages which have deep-enough `node_modules` tree.
It's because `allowList` and `globString` end up with thousands of paths, which overwhelm the `minimatch` whose input string-matcher length has to be maximum `1024*64=65K` characters.  I logged `allowList` just before it caused problem and it was around 450K characters!!!
This PR excludes `node_modules` and `.git/*` from `minimatch` inputs, because npm [automatically excludes](https://docs.npmjs.com/cli/v8/commands/npm-publish) these paths.
---
Fixes #634
Closes #635
=> Exclude node_modules and .git subpaths from minimatch input string

source/npm/util.js, test/prerequisite-tasks.js
<details>
<summary>Thank you for considering this PR</summary>
This is my first contribution to open source, so if this PR description is a bit too much, please let me know 😃 
</details>
This PR fixes the [``npm access`` error](https://github.com/sindresorhus/np/issues/665) that occurs after updating npm to version 9.0.0.
```bash
✖ Command failed with exit code 1: npm access ls-collaborators @upleveled/eslint-config-upleveled
npm ERR! code EUSAGE
npm ERR!
npm ERR! ls-collaborators is not a valid access command
npm ERR!
npm ERR! Set access level on published packages
npm ERR!
npm ERR! Usage:
npm ERR! npm access list packages [<user>|<scope>|<scope:team> [<package>]
npm ERR! npm access list collaborators [<package> [<user>]]
npm ERR! npm access get status [<package>]
npm ERR! npm access set …
```
=> Fix npm access error(#665)

readme.md
After triaging every single open issue in the repo, I collected the main and recurring issues and requests that people have with np and decided it might be best to add them to the readme. np isn't for everyone and it should be clear about that. People take "a better npm publish" a little too literally.
Relevant issues:
- https://github.com/sindresorhus/np/issues/592
- #420 
- https://github.com/sindresorhus/np/issues/619#issuecomment-994493179
- https://github.com/sindresorhus/np/issues/549
=> Add "what np isn't" section to the readme

readme.md, source/npm/handle-npm-error.js, source/ui.js
Fixes #660.
Needs test(s), but I'm not entirely sure how to test this.
=> Fix UI prompt for new publicly scoped packages

source/ui.js
The following message was missing the word `for`:
https://github.com/sindresorhus/np/blob/aa23a92bcaf710068f01ed5fe50d3039b510e223/source/ui.js#L93-L95
"The following new files will be published FOR the first time"
=> Fix missing word in `checkNewFiles`

source/prerequisite-tasks.js, source/ui.js, source/version.js, test/version.js
Closes #375.
Shows the new version in non-interactive mode (e.g. when running `np minor`) in pretty-diff form:
<p align="center"><img width="625" alt="image" src="https://user-images.githubusercontent.com/1403701/228125898-dd8049d9-3085-4378-95a7-82c1aa8ec804.png"></p>
=> Show new version in non-interactive mode

source/cli-implementation.js, source/git-util.js, source/index.js, source/ui.js, source/util.js
Closes #624.
Adds a confirmation step for new dependencies that have been added since the last release:
<p align="center"><img width="608" alt="image" src="https://user-images.githubusercontent.com/1403701/228758556-7eee362e-fd99-4274-8e2d-b3e491fa5a1e.png"></p>
It's part of the same check as for new files, so there's no additional prompts.
=> Add check for new dependencies

source/git-util.js, test/_utils.js, test/git-tasks.js, test/prerequisite-tasks.js
Fixes #421.
Fixes #414.
If `np` detects that there are unfetched upstream changes (via `git fetch --dry-run`), errors with
```
Remote history differs. Please run `git fetch` and pull changes.
```
~I'm not sure if it matters that it only checks origin. I guess if the remote name differs? Should the check be `git fetch @{u} --dry-run`?~
According to the [man page](https://git-scm.com/docs/git-fetch#_description), `origin` can be omitted:
> When no remote is specified, by default the origin remote will be used, unless there’s an upstream branch configured for the current branch.
=> Fix remote history check - check if `git fetch` needs to be run

package.json, test/new-files.js
Uses the method we added in https://github.com/sindresorhus/move-file/pull/23#event-8934219551 for a couple of fixtures from #682.
=> Use `renameFile` from `move-file` for `new-files` fixtures

source/cli-implementation.js, source/config.js, source/git-util.js, source/index.js, source/npm/util.js, source/ui.js, source/util.js, test/config.js, test/index.js, test/integration.js, test/packed-files.js
Per https://github.com/sindresorhus/np/pull/682#issuecomment-1497873231, I've made sure that `packageDirectory` is only called once, from `cli-implementation.js`. This has helped the slowness that I mentioned immensely.
Do we want to add a spinner anyway?
=> Improve startup: ensure `package.json` is only parsed once

source/npm/enable-2fa.js
This PR will add the support of 2fa with the npm version 9 and up.
I used the existing version check to determine which arguments should be used:
- `npm access set mfa publish <package>` for new versions
- `npm access 2fa-required <package>` for npm versions lower than 8
Fixes #692
=> Add 2fa support for npm version 9+

source/index.js
Fixes #705 with @timphillips's suggestion.
=> Fix skipping publish step (missing import)

source/util.js
Fixes #699. `util.getNewDependencies` currently fails on first publish, as there's no previous release to read a `package.json` from:
https://github.com/sindresorhus/np/blob/065193375f17f40f412e0e5cedda098396c8391d/source/util.js#L86-L90
#689 should add a test case for this.
=> Handle first time display of dependencies

source/ui.js
Whenever I come across one of these messages, I am unsure what this means for me.
This PR adds explanations on possible actions for the end user.
=> improve messages related to new files/dependencies

source/ui.js, source/util.js, test/util/auto-group-list.js
Fixes #690 
Per discussion with @tommy-mitchell, here is my implementation to list unpublished files in a less verbose way.
=> Group unpublished files in folders

package.json
I see that the test suite finishes in about a minute on the CI. When I run the test suite locally, it takes almost 2 minutes and then it just fails with a lot of tests timed out. The test output formatting is messed up too.
I've done some digging and I found out it's caused by GPG signing (specifically `[tag] gpgSign = true` option). Basically the test suite runs a lot of `git` commands, which in turn read from my `~/.gitconfig` file which has personal git configurations including GPG signing enabled. I'm thinking that unit tests should not be affected by the user's git config, so we should disable this.
Seems like there [isn't any option](https://stackoverflow.com/questions/23400449/how-to-make-git-temporarily-ignore-gitconfig) for git to disable reading of `~/.gitconfig`, however …
=> fix: Tests timing out locally due to GPG

source/cli-implementation.js, source/index.js, source/ui.js, test/index.js, test/ui/new-files-dependencies.js, test/ui/prompts/tags.js, test/ui/prompts/version.js
Moves creation of `packageManager` up to the CLI, instead of independently resolving it in both the UI and the index.
=> Deduplicate `packageManager` creation

source/npm/util.js
I was having an issue with `np` on `npm` version `10.5.0` and when digging into it I found that the `npm pack` command was outputting some "helpful" notes prior to the JSON.
I tried adding a `--silent` to the command, and that fixed remove the "helpfulness".
Apart from doing that, this PR also wraps the original exception in a new error that explains what kind of JSON-parsing that's failing – as that can make it a bit more easy to understand why it suddenly started failing.
My `npm` version `10.5.0`:
```
❯ npm pack --dry-run --json                                 
> @voxpelli/typed-utils@1.3.0 prepare
> husky
[
{
"id": "@voxpelli/typed-utils@1.3.0",
"name": "@voxpelli/typed-utils",
```
=> Fix json output in some npm version

source/package-manager/configs.js
Fixes half of https://github.com/sindresorhus/np/issues/738
Does not fix the bug that creates two separate tags when the prefix is missing, but makes sure that most users, who aren't interested in customising the tag, get the same `v` prefix on pnpm as they do on npm and yarn.
=> pnpm: use npm for tag-version-prefix

source/index.js, source/npm/handle-npm-error.js, source/npm/publish.js, test/index.js
symptom: hangs forever here:
```
✔ Prerequisite check
✔ Git
✔ Installing dependencies using yarn-berry
✔ Running tests
✔ Bumping version
⠦ Publishing package
```
I aborted it and tried to run the command manually and I can see that it prompts for a OTP on stdout:
```
yarn npm publish
➤ YN0000: LICENSE
➤ YN0000: README.md
➤ YN0000: index.js
➤ YN0000: package.json
✖ One-time password: · 
```
Looking at the `np` otp implementation it seems that npm and yarn v1 will exit with an error when an OTP is encountered:
https://github.com/sindresorhus/np/blob/6ee23e5c0160b2991000260cc864c15d649b04df/source/npm/handle-npm-error.js#L12
however yarn berry doesn't exit, it just prints the OTP prompt and hangs forever. this PR will help kill it off so that OTP can be prompted to the user and then re-run …
=> Fix publish otp for yarn berry

source/npm/util.js
Fixes #740 
Anyone using `np` with newer versions of Node.js and `npm >= 10` is probably running into this issue. This PR just sanitizes the `stdout` from `npm pack` to look for the first `[` character to start parsing the output JSON array, which should be backwards compatible with previous functionality.
=> fix: npm 10 bug with npm pack; issue 740

source/npm/util.js
Followup to #743 (which [failed on my testing](https://github.com/sindresorhus/np/issues/740#issuecomment-2061632602))
Fixes #740
=> Use --foreground-scripts=false for npm v10 support

source/package-manager/configs.js
Fixes the hanging of the `Publishing package` step caused by pnpm checking Git branches and waiting for stdin (this message is not visible, `np` just hangs on `Publishing package` on a non-`main`/`master` branch):
```
pnpm publish
? You're on branch "renovate/eslint-monorepo" but your "publish-branch" is set to "master|main". Do you want to continue? (y/N) › false
```
This disables the Git checks via the [`--no-git-checks` option](https://pnpm.io/cli/publish#--no-git-checks)
cc @mmkal
=> Fix np with pnpm and --any-branch or --branch

source/cli-implementation.js, source/npm/util.js, test/npm/util/is-external-registry.js
Allow `publishConfig.registry` to be `'https://registry.npmjs.org'`
~Though I uses `https://registry.npmjs.org/`, but the default value does not include the trailing slash, so I'm going to change my package.json and live with it. 😄~ Turns out both used in npm docs.
~I didn't change `isExternalRegistry` utility, since I found it's used for different purpose~ https://github.com/sindresorhus/np/pull/750#issuecomment-2230575776
Fixes #749
=> Allow `publishConfig.registry` to be npm default registry when using Yarn berry

readme.md
Change the XO code style badge to the [official version](https://github.com/xojs/xo?tab=readme-ov-file#badge).
Before:
After:
=> Change code style badge
