sindresorhus/np

readme.md

Following https://github.com/MoOx/npmpublish/pull/2

Minor change about the "Why"

---

cli.js
package.json

add `update-notifier` - fixes #31

---

cli.js
index.js
readme.md

Add `--skip-tests`, `--skip-cleanup`, and `--yolo options`

Add skip-cleanup, and yolo options, Fixes #33

---

cli.js
readme.md

Make users explicitly specify the new version

---

readme.md

Since this is using `npm version`, this will also update the `npm-shrinkwrap.json` file - https://docs.npmjs.com/cli/version#description

Add note about shrinkwrap

---

index.js
readme.md
test.js

Require the user to specify a dist-tag when publishing a pre-release version

---

lib/git.js

Fixes wording in error message.

Fix wording in error message

---

readme.md

Tip: Prerequisite step runs forever

---

readme.md

`npm version` will include any tracked files in its commit and tag:
> 3. Run the `version` script. These scripts have access to the new `version` in package.json (so they can incorporate it into file headers in generated files for example). Again, scripts should explicitly add generated files to the commit using `git add`.
> https://docs.npmjs.com/cli/version
This is likely the desired behavior when running build scripts as documented.

Document how to include files built on `npm version`

---

lib/ui.js

Hi,
it would look nice, if we highlight the difference between the old and the new version in the interactive UI.
What do you think?

Highlight version diff in the interactive UI

---

index.js

Fix Yarn version bumping behavior

---

readme.md

Add tip about publishing to gh-pages

---

.travis.yml
index.js

I could push the `.travis.yml` change separately if you want.

Do not generate package-lock.json when reinstalling - fixes #166

---

package.json

Freeze `rxjs` version

---

index.js
lib/publish.js
package.json
readme.md

This PR should resolve the OTP problem.

Add support for OTP - fixes #184

---

lib/prerequisite.js
package.json

Fixes #196 
- Ping npm registry
- Check if user logged in and has write access to the package
- Check if git remote exists and is reachable

Add network checks to prerequisite checks

---

index.js

Running `yarn install` and `npm install` in non-production mode

---

readme.md

Not sure about the wordings though...

Document adding `np` as dependency - fixes #212

---

lib/ui.js

Add `current: ` before current version in prompt

---

index.js

Cleaning up - as promised! Still hoping to look at improving tests.
ref https://github.com/sindresorhus/np/pull/220#discussion_r165832291
- Remant of debugging

Clean up unnecessary catch

---

lib/ui.js

I was thinking at two ways of fixing this. Either show a warning that there are no commits, are show a confirmation box with the message
> No commits found since previous release, continue?
I went with the second option. Feel free if you rather want the first one with just a warning.

Add confirmation message when no previous commits are found - fixes #242

---

package.json

Bump any-observable to support rxjs@6

---

lib/ui.js

This should probably be enough, but I didn't write any tests (there weren't any covering this function in the first place AFAICT, but I really just skimmed)
Closes #281

Add gitlab.com support

---

lib/ui.js

Only check for scoped repo when publish is enabled

---

lib/git-util.js
lib/ui.js

This fixes #316.
Let me know if there should be added a test for this to prevent future regressions.

Handle no previous Git tags

---

index.js

I forgot to do this as a part of #321.

Show message when skipping push

---

source/git-util.js
source/prerequisite-tasks.js
source/pretty-version-diff.js
source/release-task-helper.js
source/ui.js
source/version.js
test/version.js

This is a follow-up PR to #349.

Move version comparisons to `version.js`

---

source/npm-util.js
source/prerequisite-tasks.js

Fixes https://github.com/sindresorhus/np/issues/361

Add external registry support to authentication check

---

package.json
source/git-util.js
source/npm-util.js
source/prerequisite-tasks.js

See https://github.com/sindresorhus/np/issues/248#issuecomment-470049776 and #248.
Fixes #248

Verify installed Yarn version is >=1.7.0

---

readme.md

Fixes #154 
// cc @jesstelford @voxpelli

Add tip for releasing an update to an old version

---

source/ui.js

Closes https://github.com/sindresorhus/np/issues/376

Drop question `Will bump from X to Y. Continue?`

---

source/cli.js
source/ui.js

This fixes https://github.com/sindresorhus/np/pull/354#issuecomment-480395709 as well as https://github.com/sindresorhus/np/pull/377#issuecomment-480404680.

Fix version prompt and config

---

source/npm/publish.js

Fixes #387
// cc @edsrzf @minosss

Fix multiple version bumps when publishing using Yarn

---

source/index.js

Fixes #393
// cc @EdJoPaTo Let me know if this fixes the issue for you.

Avoid rollback after publishing a private package

---

package.json
source/git-util.js
source/index.js

Fixes https://github.com/RobinBuschmann/sequelize-typescript/issues/602#issuecomment-485439123
// cc @RobinBuschmann Let me know if this fixes the issue for you.

Avoid skipping push if branch name isn't "master"

---

package.json

Which fixes a vulnerability in js-yaml: https://www.npmjs.com/advisories/813

Update cosmiconfig to 5.2.1

---

package.json
source/git-util.js
source/npm/util.js
source/prerequisite-tasks.js
source/version.js

no tests were added/updated, since this is just a refactor. :)

Add system requirements to `pkg.engines`

---

source/index.js
source/npm/publish.js

Since this 3601af5fb7d4256cece399d4eb232c8d69fcf5a3 commit `input` is not used in publish so we can safely remove all its occurrences.

Remove unused parameter

---

source/index.js

Do not show the rollback message when the test step fails

---

source/index.js

Don't log "Aborted!" message when publish is a success

---

source/index.js

Fix incorrectly showing "Aborted!" message on successful publish

---

package.json
source/npm/util.js

Fixes https://github.com/sindresorhus/np/issues/424#issuecomment-498043582

Check package name availability in custom registry

---

source/ui.js

Don't ask for tag if `--no-publish`

---

source/ui.js

Don't check `"files"` in package.json or `.npmignore` if private package or not publishing

---

readme.md

I added the workaround for issue fixes #432 to the docs.
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#432: "Verify user is authenticated" Credentials Issue](https://issuehunt.io/repos/40806530/issues/432)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

Add FAQ section to the readme

---

package.json
source/npm/handle-npm-error.js

Fixes #291
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#291: Accept the 2FA (otp) token after 6 characters](https://issuehunt.io/repos/40806530/issues/291)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

Auto-submit 2FA

---

source/ui.js

Fixes #535 . Tested on MacOs Higher Sierra.
Any other reviewers i should tag? @sindresorhus

Fix specifying a custom version via UI

---

source/release-task-helper.js

Fix a regression from 6.3.0

---

source/git-util.js

Fixes the empty prompt (issue #588).

Fix confusing prompt with empty file list

---

source/npm/util.js
source/ui.js
source/util.js
test/npmignore.js

Add support for unpublished as well as first time published files as mention in https://github.com/sindresorhus/np/issues/588#issuecomment-751376941.

Fix showing files added since the last release

---

source/cli-implementation.js

Fix `--message` flag help description

---

package.json
source/npm/util.js
source/ui.js
test/npmignore.js

Fixes #613
@jakobrosenberg @reatexpk @michail-peterlis can one of you verify this fixes the issue for you?
// cc @bunysae

Fix files prompt when no new or unpublished files can be found

---

source/npm/util.js
test/npmignore.js

Fix error "glob pattern string required"

---

readme.md

Add note about supported yarn versions

---

package.json
source/npm/util.js
source/util.js
test/npm/util/collaborators.js
test/npm/util/prerelease-tags.js
test/util/get-pre-release-prefix.js
test/util/get-tag-version-prefix.js

Drop `ow` dependency

---

readme.md

Readme still says pnpm is unsupported.

Fix pnpm note

---

source/package-manager/configs.js

https://bun.sh/docs/install/lockfile
Bun now supports text-based lockfile so I added 
https://bun.sh/docs/install/lockfile#text-based-lockfile

Support `bun.lock` lock file
